### ISSUE TITLE
Поддержка устройства: Xiaomi Mi scale v1 and v2

### ISSUE THREAD

**Issue by GigaVik** [alutov/ESP32-R4sGate-for-Redmond#105]
Здравствуйте!
Прошу рассмотреть возможность добавить поддержку весов от Xiaomi а именно MI Scale и Mi Scale 2.
Подробное описание протокола нашлось на GitHub'е проекта openSacle - https://github.com/oliexdev/openScale/wiki/Xiaomi-Bluetooth-Mi-Scale.

**Comment by alutov** [comment]
Спрашивали за весы, думаю, добавлю. За протокол спасибо, почитаю.

**Comment by GigaVik** [comment]
Возможно еще рассмотрите добавление датчиков влажности\температуры от тех же xiaomi. 
Здесь описание данных популярной кастомной прошивки для датчика Xiaomi Thermometer LYWSD03MMC - https://github.com/atc1441/ATC_MiThermometer

**Comment by alutov** [comment]
Есть уже поддержка этих термометров.

**Comment by GigaVik** [comment]
> Есть уже поддержка этих термометров.

Блин, точно я в истории версий только сейчас увидел
Чтобы его добавить нужно выбрать устройство Mi-Unknown?

**Comment by alutov** [comment]
Все есть в в описании. Прочитайте его, пожалуйста.

**Comment by Psytoshgen** [comment]
можно свои  копеек? Yunmai color - аналог Сяомми
Протокол вот
https://gist.github.com/conoro/f0c1d96c450a8f5cce70e2846c3686c4

**Comment by alutov** [comment]
Спасибо за линки, буду изучать.

**Comment by alutov** [comment]
По протоколу вроде бы выходит, что весы mi scale отправляют вес в рекламном сообщении. Вариант предпочтительней постоянной связи. Вопрос такой, мак адрес весов не меняется? И как выглядит рекламное сообщение в мониторе шлюза.

**Comment by GigaVik** [comment]
> Owner
Мак адрес статичный.
Постоянного подключения нет, весы просыпаются в момент их активации и вещают пока идет взвешивание.
![IMG_20220909_084402](https://user-images.githubusercontent.com/25990377/189267404-ff10578b-7683-449e-8b61-f532905f65c4.jpg)


```

mac: c8:47:8c:ef:9c:4c |   | -82 dB | 0.2 s | 0.4 s | 02 01 06 03 02 1d 18 09 ff 57 01 c8 47 8c ef 9c 4c 0d 16 1d 18 02 20 44 b2 07 01 01 0d 0f 0e | s
-- | -- | -- | -- | -- | -- | --
  | c8478cef9c4c |   | -82 dB/0

```

**Comment by alutov** [comment]
Спасибо, то что нужно!

**Comment by alutov** [comment]
Не совсем совпадает с протоколом. Но по данным выходит, что время и дата 13:15:14 и 10/01/1970.  А вес 8.720 или я ошибаюсь?

**Comment by GigaVik** [comment]
> Не совсем совпадает с протоколом. Но по данным выходит, что время и дата 13:15:14 и 01/01/1970. А вес 87.20 или я ошибаюсь? Дату и время выводить?

без синхронизпции с прилржением там можнт быть любая дата.. а вот вес 87.55 был)

**Comment by alutov** [comment]
По синхронизации, если приложение установит время и дату, они там сохранятся же, или там батареи нет? 
Еще вопрос, что делать с данными. К примеру, положили что-то на весы, они включились, передали данные и выключились. В умном доме оставлять последний вес и его дату даже при отключенных весах? Или же чистить данные?

**Comment by GigaVik** [comment]
Скорее всего он уходит в глубокий сон, и ещё он вроде бы хранит всю историю взвешиваний с самого первого.
По ссылке вроде бы разбор протокола был и работы весов.
В идеале фиксировать последнее значение, 
Сейчас через бле интеграцию в home assistant данные приходят, но после перезагрузки уходят, я эту проблему решал сперва отправляя вес с весов на мктт брокер с фиксацией сообщения а потом уже в home assistant брал оттуда. 
Чтобы не обнулялись данные.
После этого у меня ещё стоит четыре отдельных сенсора на четыре разных человека, весы измеряют вес - сенсоры определяют в их ли диапазоне этот вес и сенсор каждого человека принимает эту цифру

**Comment by alutov** [comment]
Есть вот такая ссылочка: https://www.pangodream.es/read-xiaomi-mi-smart-scale-using-an-esp32. Вроде как правильно расписаны данные, приходящие в рекламном пакете. В папку jpg залил версию, можно пробовать.

**Comment by GigaVik** [comment]
> Есть вот такая ссылочка: https://www.pangodream.es/read-xiaomi-mi-smart-scale-using-an-esp32. Вроде как правильно расписаны данные, приходящие в рекламном пакете. В папку jpg залил версию, можно пробовать.

![Screenshot_20220910-153640_Chrome](https://user-images.githubusercontent.com/25990377/189479748-d12ba3c1-9e21-4285-93f3-65122923ce12.png)
![Screenshot_20220910-153535_Chrome](https://user-images.githubusercontent.com/25990377/189479760-78cf230a-9d82-4344-a1f2-233a95179c44.png)
![Screenshot_20220910-153531_Chrome](https://user-images.githubusercontent.com/25990377/189479770-38c7fc28-82f0-46fc-9d7d-daa4dfbe3979.png)
![Screenshot_20220910-154130_Chrome](https://user-images.githubusercontent.com/25990377/189479779-072c83c3-2fd3-4235-a86b-4177988dc6bf.png)

**Comment by alutov** [comment]
Нет, соединение я не делал, только в ble-мониторе.

**Comment by GigaVik** [comment]
> Нет, соединение я не делал, только в ble-мониторе. Это новая версия? И что показывает в мониторе?

да, новая вот
![IMG_20220910_160227](https://user-images.githubusercontent.com/25990377/189480356-53f34367-bea1-4962-b71e-893be23f81a8.jpg)

**Comment by alutov** [comment]
Ну вроде внизу появилось Mi Scale. А появились топики веса даты и времени? Для этого нужно тайм-аут поставить не равный 0.

**Comment by GigaVik** [comment]
![Screenshot_20220910-161258_Chrome](https://user-images.githubusercontent.com/25990377/189480727-35e4063c-08ba-4321-b940-85c68c56c1b2.png)
показывает правильно, скажи пожалуйста а там в описании протокола не написано весы вещают зафиксированный вес и не зафиксированый разными битами?
потому что те данные которые ты вывел ловят все изменения весов))

**Comment by alutov** [comment]
Так, время без цифр часов. Поправил и залил. Выводятся все данные с ненулевым весом. Вот картинка из ссылки: 
![image](https://user-images.githubusercontent.com/52620259/189481113-864ce2e6-ec67-403f-b73f-745c1229208d.png)
Бита стабилизации на ней нет. В отличие от всех остальных ссылок, где даже порядок данных иной. Я так понял, везде описывается именно соединение. Но там все можно настроить один раз в родном приложении, и больше соединение не особо и нужно, потому и не заморачивался пока. Но там автор заметил, что стабильные показания идут с правильным годом. Чтобы проверить это, надо смотреть данные в динамике. И еще, это версия vi scale 1 кажется. Во второй версии похоже есть отличия.

**Comment by GigaVik** [comment]
> Поправил и залил

нету в jpg

**Comment by alutov** [comment]
Да, забыл последнюю кнопку нажать.)

**Comment by GigaVik** [comment]
> Чтобы проверить это, надо смотреть данные в динамике. И еще, это версия vi scale 1 кажется.

Сегодня позже протестирую в динамике.
MiScale2 v1 
Есть ещё v2 там данных больше, они сами рассчитывают жир и так далее. И внешне другие немного.

**Comment by GigaVik** [comment]
![Screenshot_20220910_214210_io homeassistant companion android](https://user-images.githubusercontent.com/25990377/189493266-d76e79b1-506c-46d9-92bf-2e8962ec6aa4.jpg)

Хорошо работает
Показывает реальную дату и время по UTC, но только если весы были подключены к  офф приложению после установки батареек.
Если вынуть батарейки то соответственно дата 1970
Время и дату показывает при каждом поступившем сообщении, не важно зафиксировано или нет.
Но ble интеграция в homeassistant  каким то образом видит зафиксированный вес (возможно вес фиксируется по жёстко фиксированной выдержке времени с момента получения измерения и интеграция просто отсчитывает ровно столько же как и весы и происходит фиксация)

**Comment by alutov** [comment]
Пока оставляем так?

**Comment by GigaVik** [comment]
> Пока оставляем так?

вполне!
а можно добавить к весу единицу измерения kg?
Просто homeassistant не стоит графики без единицы измерения.

**Comment by alutov** [comment]
Добавил единицу измерения. Обновил релиз.

**Comment by GigaVik** [comment]
> Бита стабилизации на ней нет

я нашел бит стабилизации! это 5й бит 0го байта
можно пожалуйста когда будет время сделать 2 датчика веса?
1 как сейчас а второй только стабилизипованный?
![IMG_20220913_181034_649](https://user-images.githubusercontent.com/25990377/189910287-7b524620-ba87-43fd-9962-6e5df15bca77.jpg)

**Comment by GigaVik** [comment]
а еще ошибка такая, при удалении топиков mqtt из настроек шлюза,мак весов меняется на такрй же мак + в концеикуча нулей, и устройство после этого неисчитывается.
я как аоспроизведу это, отпишусь.

**Comment by GigaVik** [comment]
1
![IMG_20220913_194300_033](https://user-images.githubusercontent.com/25990377/189932309-763e1374-06e6-4dc5-959d-c272bd0c1e21.jpg)
2
![IMG_20220913_194257_813](https://user-images.githubusercontent.com/25990377/189932346-8839618b-fb0e-4ff3-8384-1b56ffe4f873.jpg)
1 и 2 как выглядит при первом появленти и добавлении

3
![-2147483648_-210217](https://user-images.githubusercontent.com/25990377/189932482-0cdb24e8-b1f5-451f-8046-6d6ad9f86ea1.jpg)
так после удаления mqtt топиков

4
![-2147483648_-210215](https://user-images.githubusercontent.com/25990377/189932711-82f6f11b-c329-4527-94da-ca953de3d71b.jpg)
и появляется новый сигнал от весов, но уже вне условия добавления (без значения интервала времени)

**Comment by alutov** [comment]
uuid поправлю, а вот с весами и 5 битом. Там кроме веса есть еще и дата. Фиксировать дату только для стабильного веса?

**Comment by alutov** [comment]
Можно пробовать.

**Comment by alutov** [comment]
По Yunmai color забыл отписаться. Протокол почитал, но там речь идет о соединении. Сделать можно, но. Шлюз постоянно поддерживает соединение. Удобно по многим причинам, главная - быстрое исполнение команд. В случае весов постоянное соединение не подходит, соединение по требованию - пока нет у меня понимания, как сделать. Для весов отличный вариант - разбор рекламного сообщения. Возможно, там есть все данные, как и в сяоми. Для начала, можно глянуть, что показывают весы в мониторе шлюза.
