### ISSUE TITLE
Отключается nightlight при кипячении (RK-G200S)

### ISSUE THREAD

**Issue by MrC0nst** [alutov/ESP32-R4sGate-for-Redmond#106]
Если включен режим nightlight то при кипячении он выключается и не включается обратно после того как чайник закипел
Вроде в прошлых версиях данный режим не выключался самостоятельно, по крайней мере в настроенной автоматизации по смене цвета все работало. 
Андрей, есть ли возможность возвращать настройки nightlight после кипячения в исходное состояние?

PS: в выпадающем списке меню нет возможности выключить nightlight, а только включить его
![image](https://user-images.githubusercontent.com/75075223/188275595-6dad0fe4-72b6-4737-857d-d065bbfcd2c2.png)

**Comment by alutov** [comment]
В принципе так всегда и было. По памяти, там настраивается 2 режима - подсветка при кипячении и подсветка при выключенном чайнике. При кипячении подсветку шлюз не использует и настройки не меняет, управляется она только при выключенном чайнике. Отдельной команды выключения подветки нет, так как она совпадает с выключением любого другого режима.

**Comment by MrC0nst** [comment]
>> Возврат подсветки после выключения любого режима в принципе сделать можно.
Да, ее можно держать всегда в режиме ON, А выключать из умного дома передавая цвет 0,0,0

**Comment by alutov** [comment]
Ночник может и не всем нужен. Я, к примеру, им не пользуюсь на 216 чайнике, а использую температурную подсветку.

**Comment by alutov** [comment]
Закинул в папку jpg версию. Если включать кипячение из шлюза, после его отработки восстанавливается ночник. Если включать кипячение на чайнике, то он восстанавливает ночник сам. Это на 216 модели.

**Comment by MrC0nst** [comment]
Только что прошился на 2022.09.14. Модель не 216 поэтому ночник отключался на версии из JPG. В автоматизации я ночник не отключаю а посылаю на него черный цвет (0,0,0).

**Comment by alutov** [comment]
Пока что пробный вариант отключения, только на восстановление ночника при включении кипячения на шлюзе. Ночник отключается и при ручном включении кипячения?

**Comment by MrC0nst** [comment]
Итак, чайник G214S, на шлюзе выбран как G200S. Мониторю через MQTT Explorer. Включение nightlight через шлюз. Кипячение чайника через кнопку на нем.
![image](https://user-images.githubusercontent.com/75075223/190966524-bf18315f-2d9f-4898-a1e1-5721f6a4b8f3.png)
До 1 подсветка включена, **1**- кипячение чайника с кнопки на нем. После кипячения подсветка работала. **2**- Снял чайник с подставки и налил воды. Подсветка сама отключилась, но потом включилась с аппаратным переливом цветов. Секунд через 30 установился цвет из HA. **3**- снял чайник и поставил рядом с платформой. Потом вернул обратно. Опять подсветка включилась с аппаратным переливом цветов а потом отключилась (начало **4**). Включил nightlight через шлюз

**Comment by alutov** [comment]
Прошивка пока что возвращает подсветку завершении кипячения, если кипячение было включено на шлюзе. Если она была включена до этого любым способом. И это пока что все. Если кипячение было включено на чайнике, он затем сам восстанавливает подсветку, без участия шлюза. Замечу походу, что при включении кипячения на шлюзе ему приходится явно выключать режим подсветки, а иначе кипячение никак не включить. А потому сильно сомневаюсь, что подсветка потом возвращалась на любой версии шлюза. При снятии с подставки и возврате поведение определяется только чайником. Да, мой чайник тоже включает подсветку при установке на подставку, потом ее выключает. Почему так сделал производитель, пока загадка.  Принудительное включение последнего режима после установки чайника на подставку пока не реализовано, пока подумываю над этим. Но нужно наверное иметь возможность его отключения.
