### ISSUE TITLE
Отправка команд из Home Assistant

### ISSUE THREAD

**Issue by Anzic23** [alutov/ESP32-R4sGate-for-Redmond#107]
Настроил связь с ХА, поставив галочку Hass Discovery. Но проблема в том, что из ХА значение управления приходит в виде ON, OFF, и шлюз на них не реагирует, реагирует только на on/true/1. Можно ли добавить в прошивку возможность "отзываться" на команды, если они пришли в верхнем регистре?
Version App / IDF | 2022.08.22 / v4.4

**Comment by alutov** [comment]
Честно говоря, не понял, очем речь. Если зайти в брокер мктт експлорером, то можно убедиться(сам только что проверил), что чайник реагирует на команды ON, on, On, oN, True, TRuE, 1 на включение и OFF, Off oFF off FalsE и 0  на выключение. Сравнение идет без учета регистра и на все варианты. Возвращается правда ON, OFF в верхнем регистре, если всключено автодискавери. Значит, из скрипта идет что-то другое, это скорее всего, так как все остальное прописывается в дискавери и глючить не должно., по крайней мере жалоб не было. Все переключатели в ха ведь работают? Я так понимаю, речь идет об яндексе? Есть вариант пока что не морочться со скриптами, а взять только сущность климата, назвать ее словом "чайник" и прокинуть в алису. После чего будут доступны команды включмть чайник( это кипячение или кипячение с последующим подогревом, если до этого был включен подогрев) выключить чайник(выключает все), установи температуру чайника 40 (включает подогрев) либо включи обогрев - это подогрев с последней установленной температурой. И, наконец, включи охлаждение - включает подсветку. Не очень красиво, но как есть. То есть основные режимы рулятся)
