### ISSUE TITLE
Чайник RK-M216S

### ISSUE THREAD

**Issue by Professor338** [alutov/ESP32-R4sGate-for-Redmond#115]
Добрый день. 
Подключал сегодня чайник "RK-M216S" по инструкции но он подключился как то не полноценно, в отличие от ваших скриншотов у меня поле state пустое, а поле status в MQTT всегда offline....

![main](https://user-images.githubusercontent.com/115339162/199843108-64593122-6883-41c3-aaed-b78684f8f08e.png)

и на вкладке подключения что то идёт не так почему то "Device not defined. " и не понимаю что нужно сделать "Store values then press Ok."

![что делать](https://user-images.githubusercontent.com/115339162/199843115-90477283-5660-4ebd-89f4-0ab6c1ee46c4.png)

**Comment by alutov** [comment]
Нужно зайти в настройки и выбрать в "TYPE" "RK-G200S" или же  "RK-G240S", без разницы. Эти пункты абсолютно одинаковы, просто задают интервал чайников 200-240, для которых выбирается этот протокол.

**Comment by Professor338** [comment]
Ура! Спасибо большое!
