### ISSUE TITLE
AM43 reversed status

### ISSUE THREAD

**Issue by akrigator** [alutov/ESP32-R4sGate-for-Redmond#116]
Проброшенные шторы в Home Assistant отображают противоположный статус, нежели отрисованный  в приложении Blind Engine, из-за этого все автоматизация переворачиваются с ног на голову.
Перешел на ESP32-R4sGate-for-Redmond с am43 из espHome, в нем статус совпадал с приложением, соответственно поэтому старые автоматизации приходится реверсить

**Comment by alutov** [comment]
Действительно, это так. Вроде бы сделано правильно, как я считаю. У меня тоже шторы работают в этом режиме. Что интересно, только так кнопки на самих шторах работают правильно - вверх идет вверх, вниз - вниз. Режим определяется шлюзом по биту статуса. Очень странно, почему нигде больше так не сделано, включая родное приложение и esphome. Хотя видел на гите esphome запрос на эту фичу. Это вторая причина. 
И да, в исходниках пока не поправлена ошибка при работе с разделенными топиками, жду датчики). В бинарниках все поправлено.
