### ISSUE TITLE
Не подключается к серверу MQTT

### ISSUE THREAD

**Issue by Malaysk** [alutov/ESP32-R4sGate-for-Redmond#119]
Здравствуйте. Залил самую последнюю прошивку, скачанную сегодня. Все как бы работает (чайник, мультиварка), но не подключается к MQTT , все время написано - MQTT connection count / state | 0 / Disconnected
Хотел спросить, есть какие то проблемы, если имя пользователя с большой буквой? Все другие девайсы без проблем подключены и работают, только с R4sGate проблема.
Уже и перепрошивал и менял все настройки и т.д. - не подключается к серверу MQTT (находится брокер в Home Assistent)

**Comment by alutov** [comment]
Могут быть проблемы с символами @ или чем-то подобным в логине или пароле.

**Comment by Malaysk** [comment]
Как раз в пароле есть такой символ. Подключено около 60 девайсов к MQTT, это надо будет всю сеть переделывать из за одного символа ?

**Comment by alutov** [comment]
Тогда придется немного подождать.

**Comment by Malaysk** [comment]
Спасибо! Конечно подожду!

**Comment by alutov** [comment]
Попробуйте файл из папки jpg.

**Comment by Malaysk** [comment]
Отлично! Моментально все соединилось! Спасибо!

**Comment by alutov** [comment]
Давно надо было передавать логин пароль отдельными полями, а не в общей строке "логин:пароль@сервер". Просто не думал, что многие используют эти символы в пароле.

**Comment by Malaysk** [comment]
А я всю голову сломал сегодня, целый день провозился, а результата небыло. Да, знаю о такой проблеме - "логин:пароль@сервер" , не первый раз проблема возникает с спецсимволом :-) . Еще раз спасибо, что так оперативно сделали.

**Comment by Malaysk** [comment]
Можно еще один вопрос в этой ветке ? Пытаюсь подключить mi smart scale 2.
Указал MAC адрес , выбрал Scan MiID.
На общей странице вот так
![Screenshot_3](https://user-images.githubusercontent.com/22643931/202510329-fa014f40-fd58-4b9f-b184-4bc7c363a673.png)
Встал на весы для сопряжения.....и ни в какую. Подскажите как правильно ?

**Comment by alutov** [comment]
Весы не нужно подключать. Нужно активировать BLE монитор, выбрав в настройках BLE monitoring-> Passive. Затем сохраняем, далее заходим на вкладку монитора, находим там весы. В поле "Name/Type" должно быть Mi Scale. В этой строке ставим тайм-аут, скажем, 60 секунд и нажимаем Ok. Все, весы прокинутся в мктт и в устройства Home Assistant.

**Comment by alutov** [comment]
Scan MiID -  это опция для поиска продукт айди чайников MiKettle. Их оказалось пока только 3. Появилась при добавлении этих чайников, потом не стал убирать, правда, недавно переименовал. И все равно с этой опцией народ пытается подключить термометры и весы Xiaomi.

**Comment by Malaysk** [comment]
Спасибо за подробную информацию! Все прочитал на главной странице предварительно, но именно по весам не нашел способа подключения :-) Теперь все идеально понятно!

**Comment by alutov** [comment]
Брокер поддерживает русские буквы, дальше не пробовал пока что.
