### ISSUE TITLE
Кофеварка RCM-M1519S не выключается 

### ISSUE THREAD

**Issue by notabene00** [alutov/ESP32-R4sGate-for-Redmond#124]
Кофеварка не реагирует на команду выключения.
Остальное работает - крепость, блокировка, статус задержки, часы - всё "забирается".
<img width="1024" alt="Снимок экрана 2022-12-19 в 02 07 23" src="https://user-images.githubusercontent.com/9576189/208324171-34df1b87-a15d-4813-b3ea-c5d6dabc18ac.png">
Включение работает по `.../cmd/state -> 1`
Выключение по `.../cmd/state -> 0` - не работает

**Comment by alutov** [comment]
А какая версия?

**Comment by notabene00** [comment]
Version App / IDF / CPU Clock / CPU Rated | 2022.12.10 / v4.4-dirty / 160MHz / 240MHz

Изначально оно и не включалось, и не выключалось. 
Подключился через родное приложение, обновил прошивку кофеварки на последнюю доступную.
Теперь не работает только выключение.

**Comment by alutov** [comment]
Нет, обновление не повлияло. Это я поломал в попытках оптимизации. Поправил и закинул в папку jpg, там всегда времянки выкладываю. Можно пробовать. Чуть поправлю еще и на днях будет новая вчерсия.

**Comment by notabene00** [comment]
> Поправил

Да, проблема решена. Спасибо за большую работу :)

**Comment by notabene00** [comment]
Пока этот канал коммуникации еще не закрыт, задам вопрос здесь.
Хотелось бы понять: возможно ли выставить время на кофеварке на текущей версии прошивки.
В описании не нашел подобной функциональности, мобильное приложение делает это автоматом.
Но после переподключения к ESP время слетает.
Если сейчас невозможно и возьметесь реализовать, открою отдельный issue.

**Comment by alutov** [comment]
Речь о часах в кофеварке? Шлюз периодически посылает команду установки времени, если сам смог получить его с ntp сервера. В вебе шлюза время и дата отображаются правильно?

**Comment by notabene00** [comment]
А, черт. 
Я всё умнодомовое от глобальной сети отрезал. 
Понял, спасибо.

**Comment by alutov** [comment]
Поправлено в версии 2022.12.29.
