### ISSUE TITLE
Feature Request. MQTT command for refresh picture.

### ISSUE THREAD

**Issue by exotsk** [alutov/ESP32-R4sGate-for-Redmond#126]
Андрей, можно сделать галку обновление картинки по MQTT команде ? для видеодверных звонков полезно.
И реально ли  сделать ресайз картинки чтобы вписать в экран ? У меня подхватывает картики от 480, влазит в литмит памяти. Но показывает конечно же уголок.

**Comment by alutov** [comment]
По порту не могу пока сказать ничего, по масштабированию надо глянуть и вспомнить, что может  jpeg декодер. Обновление картинки возможно как локальной кнопкой, так и по  мктт, если писать в топик jpg_time любое ненулевое значение.

**Comment by exotsk** [comment]
если писать в топик jpg_time любое ненулевое значение.
здесь понятно, спасибо, можно отправить любое  большое, 
подгон размера был был бы пригоден. иначе придется поднимать что-то извне, если есть ресурс, то лучше локально.

**Comment by alutov** [comment]
В папку jpg залил тестовую версию с масштабированием изображения. В декабрьской версии Home Assistant появилась вохможность вывода текста. И теперь можно управлять выводом картинки из интерфейса ХА.

**Comment by exotsk** [comment]
Спасибо, работает,  но масштабирует как то странно, примерно 20-25% процентов не дорастягивает по ширине и высоте картинку (480х270) и порт так же не

**Comment by alutov** [comment]
Масштабирование в декодере только 1:1, 1:2, 1:4. Если ширина больше 320 1:2, больше 640 1:4. Про лапы кота как раз думал, экран должен очищаться при приходе любой команды по мктт. Можно, правда еще центровку по горизонтали сделать.

**Comment by exotsk** [comment]
Про масштаб понял. Болько если экран очистить, будут белые границы ? мне кажется лапы кота лучше :)

**Comment by alutov** [comment]
Залил версию с центровкой.

**Comment by exotsk** [comment]
C центровкой вроде симпатично стало 👍🏻 
но порт
![image](https://user-images.githubusercontent.com/54969124/209319883-04d9d958-693c-42e2-9930-ece3703ffd89.png)
![image](https://user-images.githubusercontent.com/54969124/209319948-3b11e683-894f-47c5-877c-c3897962c5c4.png)

**Comment by alutov** [comment]
Ну уже и не знаю, что еще можно сделать. Можно включить Uart Debug и посмотреть, не испортил ли шлюз строку. И еще может нужно писать https, а не http. Шлюз в этом плане деревянный, автозамены делать не умеет, куда послали, туда и идет.)  Для проверки залил на гит тестовую картинку и в этой строке указал порт: https://raw.githubusercontent.com:443/alutov/ESP32-R4sGate-for-Redmond/master/jpg/tst.jpeg
У меня работает.

**Comment by exotsk** [comment]
![image](https://user-images.githubusercontent.com/54969124/209333633-15ba565f-8ef6-4438-9b49-b8fc6279e269.png)
![image](https://user-images.githubusercontent.com/54969124/209333668-464e83cb-7d52-4f9e-8942-811a162781f3.png)

**Comment by alutov** [comment]
Может быть такое, что картинка приходит в текстовом виде, похоже на html. Браузеры этот формат пони мают и уже сами преобразуют его в картинку. За jpeg не скажу, а вот с такими png файлами встречался.

**Comment by exotsk** [comment]
Вполне возможно. Ну зато исключил возможный баг для других в будущем, сервак у меня для ретрансляции данных HA по http внутри локалки. иначе с https приходится выпускать наружу много лишнего.

**Comment by alutov** [comment]
Пока это в тестовой сборке. А что описывать? Если включить Hass Discovery, в r4sGate появляются поле для ввода url и поле для ввода времени обновления. И кнопка обновления картинки.

**Comment by exotsk** [comment]
аа, всё понял! ну это круто, хотя у тебя итак все можно через mqtt затолкать :)

**Comment by artt652** [comment]
> Ну уже и не знаю, что еще можно сделать. Можно включить Uart Debug и посмотреть, не испортил ли шлюз строку. И еще может нужно писать https, а не http. Шлюз в этом плане деревянный, автозамены делать не умеет, куда послали, туда и идет.) Для проверки залил на гит тестовую картинку и в этой строке указал порт: https://raw.githubusercontent.com:443/alutov/ESP32-R4sGate-for-Redmond/master/jpg/tst.jpeg У меня работает. Вот лог: I (1655189) R4S: Url: https://raw.githubusercontent.com:443/alutov/ESP32-R4sGate-for-Redmond/master/jpg/tst.jpeg I (1656259) R4S: HTTP_EVENT_ON_CONNECTED I (1656459) R4S: Status = 200, content_length = 9476, offset_length = 9476

Андрей, здравствуйте! Есть предложение - сделать чтобы сообщения об ошибке выводились в  нижнюю статусную строку,  а на экране оставалась загруженная ранее картинка, (в настоящий момент ошибки показываются на коте )

**Comment by alutov** [comment]
При ошибке достаю кота потому, что не понятно, что до этого было на экране, но подумать можно. Вот сегодня удачно получилось с загрузкой картинок с разрешением выше 320 * 176. А раньше даже и не пытался делать, думал, что памяти однозначно не хватит. Пытался резать строку адреса при ошибке с двоеточием. При получении такой строки шлюз уходил в постоянную перезагрузку. Похоже, драйвер хттп не совсем корректно отрабатывает или я чего-то еще не учел.

**Comment by alutov** [comment]
Добавлено в версии 2022.12.29.
