### ISSUE TITLE
 HA не  получает данные с устройств

### ISSUE THREAD

**Issue by DIMMonchik** [alutov/ESP32-R4sGate-for-Redmond#132]
После обновления с 2022.04.23 на 2023.01.05 HA не  получает данные устройств хотя шлюз их получает. В чем может быть причина?

**Comment by alutov** [comment]
Изменены топики устройств в шлюзе в номером 0. В новых версиях эти топики используются для отслеживания меток несколькими шлюзами. После перехода со старых версий нужно включить BLE Monitoring в настройках, выбрав Passive, Active или Auto, отметить пункт Delete Mqtt Topics и сохранить настройки. После перезагрузки шлюз удалит лишние топики и создаст их заново. Затем, при необходимости, BLE Monitoring можно отключить.
