### ISSUE TITLE
Мультиварка RMC-M92S не подключается.

### ISSUE THREAD

**Issue by KaportsevIA** [alutov/ESP32-R4sGate-for-Redmond#133]
Доброго времени суток.
Решил попробовать подключить мультиварку к шлюзу. Не хочет, при том что чайник подключается влет.
А тут в статусах висит вот такое.
![Снимок экрана 2023-01-15 135115](https://user-images.githubusercontent.com/98884453/212536669-43ca6bb5-8eb5-4353-86a7-8fe061043280.png)
![Снимок экрана 2023-01-15 135136](https://user-images.githubusercontent.com/98884453/212536670-3d6bef30-ff11-49b8-a978-04807aaa3d16.png)
![Снимок экрана 2023-01-15 135212](https://user-images.githubusercontent.com/98884453/212536671-85d9962f-07c8-4fb3-a428-d3f7710c3842.png)

На мультиварке кнопку "Час" зажимал для сопряжения.

**Comment by alutov** [comment]
У меня на 800 вроде таймер нажимать нужно.

**Comment by KaportsevIA** [comment]
На M800 да, таймер-отсрочка, А на M92 - "Час"

**Comment by KaportsevIA** [comment]
<html>
<body>


mac: ec:33:91:77:62:c4 | RMC-M92S | -77 dB | 0.0 s | 99.9 s | 09 09 52 4d 43 2d 4d 39 32 53 02 01 05 | s
-- | -- | -- | -- | -- | -- | --
  |   |   |   |   |   | 11 07 9e ca dc 24 0e e5 a9 e0 93 f3 a3 b5 01 00 40 6e


</body>
</html>

**Comment by alutov** [comment]
Судя по первой картинке не проходит авторизация, стало быть кнопка не срабатывает. Тут подсказать точно не смогу, на руках такой нет. По розеткам помню, что надо держать до сигнала, а дальнейшее удержание кнопки приводит к очистке всех имеющихся привязок. Может быть нужно подобрать момент нажатия. Либо рестартануть шлюз в момент нажатия кнопки.

**Comment by alutov** [comment]
Как вариант может быть нужно обновиться через родное приложение редмонда, если прошивка сильно старая. Опять же, сам не сталкивался, но, говорят, такие случаи были.

**Comment by alutov** [comment]
И еще по бле монитору интересный момент. прошло 99 секунд с момента принятия последнего пакета. У меня 800 мультиварка перестает слать рекламные пакеты после соединения. Может и 92 с чем-то соединилась в итоге?

**Comment by alutov** [comment]
И как вариант, можно попробовать обновить шлюз прошивкой из папки jpg.

**Comment by alutov** [comment]
Поправлено в версии 2023.01.17.

**Comment by alutov** [comment]
В 17 версии, похоже, авторизация тоже не проходила. Вроде как должно работать в версии 2023.01.18

**Comment by alutov** [comment]
Поправлено в версии 2023.01.18.
