### ISSUE TITLE
Redmond SkyKettle RK-M173S-E

### ISSUE THREAD

**Issue by solomatinma** [alutov/ESP32-R4sGate-for-Redmond#135]
Привет, что нужно чтобы добавить этот чайник?

**Comment by alutov** [comment]
Выбрать в списке устройств RK-M173S.

**Comment by solomatinma** [comment]
что не пытался сделать, не коннектится, в родное приложение и шлюз на андроиде добавляется

**Comment by solomatinma** [comment]
Через шлюз он показывает адрес устройства, но esp с таким адресом не видит ни чего

**Comment by alutov** [comment]
Чайник поддерживает только одно соединение. Нужно отключить блютус на андроиде, чтобы есп увидела чайник.
