### ISSUE TITLE
А нельзя ли доработать ваш шлюз для такого чайника ??

### ISSUE THREAD

**Issue by tarasfrompir** [alutov/ESP32-R4sGate-for-Redmond#14]
Авторизация и все остальное описано тут 
https://github.com/aprosvetova/xiaomi-kettle

**Comment by alutov** [comment]
Даже не знаю, что сказать... Теоретически можно, я смотрел бегло эту страничку, там чайник не включается, только поддерживается. Подумал тогда, что оно того не стоит.

**Comment by tarasfrompir** [comment]
Там бы только функцию авторизации поправить, да функцию для отправки  команды - я уже и так и сяк а оно мне ни в какую... Человек просит - а я профан опростоволосился...
А чего не включается ? 

Хеатинг жеж есть вроде
![image](https://user-images.githubusercontent.com/3198716/98127588-8bebb800-1ebf-11eb-8b40-91b08fbd6e5a.png)

**Comment by DivanX10** [comment]
Главное, чтобы эту прошивку не сломали ). Все же она чисто для Redmond. Если будете добавлять чайник xiaomi в прошивку для Redmond, то лучше сделать отдельную прошивку для Xiaomi.

**Comment by tarasfrompir** [comment]
Да я ж не против - только за

**Comment by alutov** [comment]
Разве уже нет готовых решений? Чтобы это сделать, надо чайник покупать как минимум.

**Comment by tarasfrompir** [comment]
> Разве уже нет готовых решений? Чтобы это сделать, надо чайник покупать как минимум.

если бы было - не просил бы - или ткните носом....

**Comment by alutov** [comment]
Обещать ничего не буду. Чайник заказал.

**Comment by alutov** [comment]
Добавил чайник MiKettle, можно пробовать.

**Comment by tarasfrompir** [comment]
> Добавил чайник MiKettle, можно пробовать.

Пасибулечки огромное

**Comment by tarasfrompir** [comment]
есть в коннекте мажордомо регистрация ?

**Comment by alutov** [comment]
Нет регистрации, оно мне не нужно.

**Comment by tarasfrompir** [comment]
> Нет регистрации, оно мне не нужно.

Да там у меня немного русских денег есть - больше пока благодарить нечем

**Comment by alutov** [comment]
В принципе не нужно.

**Comment by tarasfrompir** [comment]
А можно пример команды через ВЕб - любой

**Comment by alutov** [comment]
Не понял вопрос, зачем? Чайник подсоединили к шлюзу? Если да, то при входе на страничку управления он должен написать "Press "Warm" on MiKettle to remote device control". Нажимаете сенсор "Warm" на чайнике и открывается меню управления. Управлять можно только из этого режима, в доке это отмечено, как впрочем и в вебе.

**Comment by tarasfrompir** [comment]
Я прошу прощения мои выражовувания не верны
вот это  можно описать в текущей реализации ? или только МКЮТТ ?
HTTP:
http://r4sgate.local/r4s/[devid]/off - выкл.
http://r4sgate.local/r4s/[devid]/heat?temp=60 - нагрев
http://r4sgate.local/r4s/[devid]/boil - кипячение
http://r4sgate.local/r4s/[devid]/boil?temp=95 - кипячение и нагрев

**Comment by alutov** [comment]
Http шлюз не поддерживал никогда.  Либо web, либо Mqtt.

**Comment by WildeRNS** [comment]
Спасибо за отличную и главное рабочую прошивку для чайника Xiaomi Mi Kettle!
Есть пара вопросов: 
1. После подключения напрочь пропадает возможность работы чайника из MiHome (чтобы возобновить работу, приходится удалять чайник и заново добавлять), так задумано?
2. Нельзя ли добавить галочку retain,чтобы при снятии/установки чайника с бази, предыдущая температура не сбрасывалась на 0? (Использую Home Assistant)

**Comment by alutov** [comment]
1. Нельзя пока что. Шлюз при подключении использует свой ключ, а не берет из михома. И использует полную процедуру. Смарт полную процедуру использует только при добавлении. Чайник похоже запоминает одно соединение.
2. Поправлено уже, это привет от совмещенных топиков. Если использовать раздельные, то и на текущей версии дефекта не будет.
3. По поводу http при написании не сильно разбирался, что там реально ходит, а сейчас нет времени. Есть проблемы с бле на есп32, в описании это есть, копаюсь с этим, пытаюсь локализовать.

**Comment by tarasfrompir** [comment]
> 1. Нельзя пока что. Шлюз при подключении использует свой ключ, а не берет из михома. И использует полную процедуру авторизации при каждом соединении. Смарт полную процедуру использует только при добавлении. Чайник похоже запоминает одно соединение при работе по упрощенной процедуре авторизации.
> 2. Поправлено уже, это баг-привет от совмещенных топиков. Если использовать раздельные, то и на текущей версии дефекта не будет.
> 3. По поводу http при написании не сильно разбирался, что там реально ходит, а сейчас нет времени. Есть проблемы с бле на есп32, в описании это есть, копаюсь с этим, пытаюсь локализовать.

Решил через curl - вроде работает

**Comment by ZL0V0N** [comment]
Добрый день. Можно добавить поддержку Redmond G203S ?
