### ISSUE TITLE
Сенсор *_kettle_ontime

### ISSUE THREAD

**Issue by Enzokot** [alutov/ESP32-R4sGate-for-Redmond#141]
Нome assistant версии 2023.2 после старта системы в логах предупреждение:
`2023-02-04 12:40:01.464 WARNING (MainThread) [homeassistant.components.sensor] Sensor sensor.r4s01_kettle_ontime has device class None, state class total_increasing and unit None thus indicating it has a numeric value; however, it has the non-numeric value: 113:12:25 (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22`
Видимо нужно передавать числовое значение и добавить `device_class: duration`

**Comment by alutov** [comment]
Добавил device_class: duration. Файл в папке jpg. Вроде у меня не ругается, но нужно еще проверить. Надо сказать, в логе полно ошибок. Например, расход в m3/h и класс water несовместимы, это допустимо только для газа.

**Comment by Enzokot** [comment]
Чтобы не было в *_kettle_ontime ошибки, значение должно быть int, а сейчас судя по скриншоту - string.
<details><summary>Скриншот</summary>

![image](https://user-images.githubusercontent.com/43236573/216889423-04c134bf-44e6-45bc-8cd1-865b063e8190.png)

</details>

**Comment by alutov** [comment]
Значит, уберу все атрибуты. Если ХА такой тупой и не понимает длительность в часах минутах и секундах.

**Comment by Enzokot** [comment]
Атрибуты то правильные и они собираются потом в Long-term Statistics, просто система никак не сможет собрать статистику по строке https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics
Вот к примеру другой +/- аналогичный сенсор:
![image](https://user-images.githubusercontent.com/43236573/216894260-ad174aa4-e8c8-404b-b004-7c4cfd41444a.png)

**Comment by alutov** [comment]
Время в секундах. Для ХА хорошо, конечно, для других систем не знаю. Наглядности меньше стало.

**Comment by Enzokot** [comment]
В качестве предложения, может сделать отдельное значение для ХА, например working_time_int и топик discovery перевести на числовое значение?

**Comment by alutov** [comment]
Пусть уже будет в секундах.)

**Comment by alutov** [comment]
Посмотрел сейчас у себя. Вроде и не ругается, но статистику отображает неправильно.

**Comment by Enzokot** [comment]
У меня в логах тишина, отображается в интерфейсе корректно. В статистике предлагает сохранение. На мой взгляд идеально.
![image](https://user-images.githubusercontent.com/43236573/216899963-85d9e119-6214-42c9-bc0d-e2880068d65a.png)

**Comment by alutov** [comment]
Оставляем так.

**Comment by Enzokot** [comment]
Большое спасибо за исправления!
