### ISSUE TITLE
Создание топиков MQTT

### ISSUE THREAD

**Issue by pmaster555** [alutov/ESP32-R4sGate-for-Redmond#148]
Удалил старые топики, он по идее должен создать заново, создает .. но.
![изображение](https://user-images.githubusercontent.com/22826842/232416130-ba0f8229-efb1-4a38-abd2-0c8b43c0c407.png)

если удалить и перезапустить есп, каждый раз прибавляется еще одно вложение )

**Comment by alutov** [comment]
Что-то не очень похоже на баг шлюза. Топики всегда создаются в корневой папке. Может с брокером что-то не так?

**Comment by pmaster555** [comment]
iobroker, шлюз там не единственный по mqtt.  но чудачит только он так..
сейчас спецом стер флешку на есп, залили прошивку заново, настроил. первый пуск норм. Если удалить status из ветки, то начинается.
![изображение](https://user-images.githubusercontent.com/22826842/232530215-3b46b44c-8a21-4143-95c2-3db89389ecba.png)

**Comment by pmaster555** [comment]
и еще заметил
![изображение](https://user-images.githubusercontent.com/22826842/232540914-c612c66c-a6c2-4f76-b014-f32dd2c05b74.png)

зачем он в обе папки пишет?

**Comment by alutov** [comment]
Что касается iobroker-ского встроенного брокера. Когда сам им пользовался, заметил, что при попытке записи относительно большого количвества топиков при старте шлюза некоторые прописываются, скажем так, с защитой от дальнейшей записи. Чтобы вернуть работоспособность, приходилось ручками удалять дефектные топики, чтобы затем шлюз прописал их еще раз. Это было отмечено в описании шлюза. Далее всплывали еще странности вроде замены данных вида "255,255,255" на "YYY". Ну а терпение кончилось, когда в одной из новых версий брокера было добавлено  неотключаемое автоматическое определение типа данных. Перешел на HA с mosquitto брокером, все проблемы ушли,  Возможно, стоит в брокере поиграться настройками, в частности, увеличить размер данных в топиках,  и отключить Hass Discovery. Сейчас тестировать шлюз с iobroker не имею возможности. Что касается "дублирования", это не баг, а фича. В папке r4s выводится лучший уровень сигнала метки от нескольких шлюзов и номер шлюза, принимающий этот сигнал. Подробнее в описании.
