### ISSUE TITLE
Поддержка чайника Xiaomi Viomi V-SK152A

### ISSUE THREAD

**Issue by Saniksanik** [alutov/ESP32-R4sGate-for-Redmond#15]
Для поддержки данного чайника в прошивке нужно добавить новый тип оборудования, полностью аналогичным MiKettle 275, но ID должен быть 1116. Я внес правку в прошивку сам и чайник отлично работает

**Comment by alutov** [comment]
Подскажите, это какой регион, как его назвать?

**Comment by Saniksanik** [comment]
У меня он EU. Viomi e-152, отличительная черта - собственный дисплей с клавиатурой

**Comment by alutov** [comment]
Добавил. Есть вопрос. Если выключить эту модель чайника  из шлюза(heat_temp =0), подождать, пока перейдет, он пискнет при этом, то при снятии и установке на подставку чайник выходит в режим "keep warm"?
