### ISSUE TITLE
Поддержка ST7789V TFT

### ISSUE THREAD

**Issue by JimiGun** [alutov/ESP32-R4sGate-for-Redmond#156]
Планируете ли Вы добавить поддержку экранов на чипах ST77* (ST7735, ST7789V, etc.)? В Китае сейчас всё более популярнее становятся и дешевле ili9341.

**Comment by alutov** [comment]
Пока не планировал. Сейчас у меня нет доступа ни к aliexpress, ни к ebay.

**Comment by alutov** [comment]
Добавил поддержку ST7789 в версии 2023.08.22. Вроде работает, нужно еще тестировать.
