### ISSUE TITLE
Поддержка Ethernet модулей 

### ISSUE THREAD

**Issue by Dorozhko** [alutov/ESP32-R4sGate-for-Redmond#160]
Добрый день!

Прошу добавить поддержку девайсов с ethernet модулями, например: wt32-eth01, Olimex ESP32, ESP32-Ethernet-Kit или 
встраеваемых модулей таких как: W5500, LAN7820 etc.

e.g. [https://github.com/1technophile/OpenMQTTGateway](url)
Заранее спасибо!

**Comment by alutov** [comment]
Честно говоря, не понимаю, зачем в шлюзе нужна поддержка Ethernet модулей. Больших объемов данных шлюз не пересылает и не получает. А поддержка требует как заметное количество ног есп, часть из них к тому же жестко привязана, так и дополнительное процессорное время.

**Comment by alutov** [comment]
Понятно. Пока в планах нет.
