### ISSUE TITLE
Home Assistant 2023.8 requires different device name

### ISSUE THREAD

**Issue by slydiman** [alutov/ESP32-R4sGate-for-Redmond#161]
После обновления Home Assistant на 2023.8 ругается:
```
Discovered entities with a name that starts with the device name

Это приведет к неисправностям в версии 2024.2.0. Пожалуйста, устраните эту проблему перед обновлением.
Some MQTT entities have an entity name that starts with the device name. This is not expected. 
To avoid a duplicate name the device name prefix is stripped of the entity name as a work-a-round. 
Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

List of affected entities:

climate.r4s01_kettle_temp
sensor.r4s01_kettle_rssi
switch.r4s01_kettle_heat
switch.r4s01_kettle_boil
sensor.r4s0_gate_rssi
button.r4s0_gate_restart
```
В Home Assistant discovery к примеру entity name `r4s01.Kettle.temp` и device name `r4s01.Kettle`. 
Нужно чтобы entity name не начиналось с device name. К примеру сделать device name `r4s01.Kettle.device`.

**Comment by alutov** [comment]
Наверное, не прокатит(. Думаю добавить в начале имени устройства d: dr4s01.Kettle. На днях обновлюсь и проверю.

**Comment by alutov** [comment]
Сделал первую букву имени устройств большой. Бинарный файл в папке jpg.

**Comment by slydiman** [comment]
Работает. Предупреждение ушло.

**Comment by alutov** [comment]
Это временное решение. Пересмотррю еще все имена, чтобы все в ХА было красиво.

**Comment by slydiman** [comment]
Ну всего девайсов максимум 5, на практике 1-2. Мак адрес тут выглядит излишним.
Там главное чтобы имена не начинались одинаково, именно чтобы entity name не начинался с device name (целиком).
Проверяется if entity.name.startsWith(device.name).
То есть мой вариант `r4s01.Kettle.device` должен работать.
А отличие в регистре букв - не очень решение, в будущем startsWith() с игнором регистра может дать ту же проблему.

**Comment by KaportsevIA** [comment]
Я имел ввиду МАК-самого ESP32-WiFiмодуля. Он точно у плат уникальный.

**Comment by alutov** [comment]
Переделал имена. Для корректного измененеия сущностей желательно выбрать в настройках Delete Mqtt Topics.

**Comment by Enzokot** [comment]
@alutov сейчас получается вместо `switch.r4s01_kettle_boil` остается `switch.boil`?

**Comment by alutov** [comment]
Ну да. Раньше шлюз пытался делать уникальное имя, прибавляя в качестве префикса имя устройства. Сейчас HA делает это сам.
