### ISSUE TITLE
LYWSD03MMC xiomi temp hum

### ISSUE THREAD

**Issue by vokforever** [alutov/ESP32-R4sGate-for-Redmond#163]
Hello! I can't binding LYWSD03MMC
I change firmware to custom,  select  binding device on rcs-51s, have icon Bluetooth on display, but always
 "Weather ATC_50E498 not connected"..
Please help

**Comment by alutov** [comment]
The gateway only supports these thermometers in BLE Monitor mode. You need to activate BLE Monitor in the settings, and then find a thermometer in the monitor tab (in the "Name / Type" column there will be the line "LYWSD03MMC"), set the Timeout, for example, 400 seconds and click Ok.
