### ISSUE TITLE
Будет ли работать чайник от бренда RED

### ISSUE THREAD

**Issue by ChapayTv** [alutov/ESP32-R4sGate-for-Redmond#172]
Хотел этот [вот](https://ozon.ru/t/e80ZyD8)  чайник взять, но разобрали. Есть абсолютно [такой](https://ozon.ru/t/Wr81yJd)  же по виду но RED, хотелось бы узнать будут ли они работать с данным шлюзом? Это вроде как просто ребрендинг компании.

**Comment by alutov** [comment]
Если ребрендинг, то, думаю, дожен. У меня 216, по виду точно такой же.

**Comment by ChapayTv** [comment]
> Если ребрендинг, то, думаю, дожен. У меня 216, по виду точно такой же.

Заказал, после 22 напишу результат

**Comment by ChapayTv** [comment]
Чайник отлично законектился, это тоже самое.
