### ISSUE TITLE
Подключение мультикухни RMK-FM41S

### ISSUE THREAD

**Issue by Anton-Ka** [alutov/ESP32-R4sGate-for-Redmond#182]
При попытке подключить к мультикухне RMK-FM41S BLE Activity показывает сначала статус "Connecting RMK-M41S (Open)", потом "Connecting RMK-M41S (Auth)", потом снова "Connecting RMK-M41S (Open)". После чего мультикухня пикает и соединения не происходит.
При этом сканер её находит, определяет имя и мак-адрес.
Перепробовал все мультиварки из списка - ничего не меняется.
Сейчас настройки такие:
![image](https://github.com/alutov/ESP32-R4sGate-for-Redmond/assets/74901464/03e444f1-ef88-48a7-92b9-ad9161de4391)
Вот так на главном экране:
![image](https://github.com/alutov/ESP32-R4sGate-for-Redmond/assets/74901464/3fb409c3-fd0f-4e33-b43e-4f3270d6c5c5)
Подскажите, как можно её подключить к шлюзу и добавить в Home Assistant?

**Comment by alutov** [comment]
Вообще-то пока мультикухня шлюзом еще не поддерживается, но соединяться должна. Похоже, не прошла привязка мультикухни к шлюзу. Нужно зажать ту же кнопку, что и при сопряжении ее со смартфоном до какого-то сигнала. Точнее не подскажу.

**Comment by Anton-Ka** [comment]
> Нужно зажать ту же кнопку

Помогло, Спасибо!
Есть все режимы, кроме:
- Десерты
- Экспресс
- Разогрев

**Comment by alutov** [comment]
В папке test есть версия с русскими названиями программ.

**Comment by Anton-Ka** [comment]
> В папке test есть версия с русскими названиями программ.

Только что закачал для проверки. Не заметил отличий. В предыдущей установленной версии названия были такими же, двойными - впереди на английском, после - на русском.
А есть ли способ прописать русские названия программ а ХА?

**Comment by alutov** [comment]
Разве сейчас в ХА нет русских названий программ?

**Comment by Anton-Ka** [comment]
> Разве сейчас в ХА нет русских названий программ?

Ну они комбинированные.
![Screenshot_2024-01-02-12-24-08-75_c3a231c25ed346e59462e84656a70e50](https://github.com/alutov/ESP32-R4sGate-for-Redmond/assets/74901464/b64ccd67-c36e-4856-894e-a9c14402ce59)
Я что-то подумал, что через локализацию будет полный перевод.
