### ISSUE TITLE
Xiaomi Mi Temperature and Humidity Monitor LYWSDCGQ/01ZM

### ISSUE THREAD

**Issue by QuAzI** [alutov/ESP32-R4sGate-for-Redmond#188]
Не могу подключить довольно старый датчик от Xiaomi, он видится в BLE, но данных с него полезных (температура, влажность) не парсится. И BLE KEY не спрашивается как для LYWSD03MMC, например.

![36d35cfc4fce45b3648883e64535945d](https://github.com/alutov/ESP32-R4sGate-for-Redmond/assets/1897605/566ccfb1-db7f-4115-9b99-9ab6cb20d253)

В BLE monitor выглядит так
![image](https://github.com/alutov/ESP32-R4sGate-for-Redmond/assets/1897605/9454c016-9767-4d17-8e74-506d8a3b190e)

Вроде бы эта железка так же известна как MJ_HT_V1 и поддержана в [ESP Home (Bluetooth BLE proxy)](https://esphome.io/components/sensor/xiaomi_ble.html#lywsdcgq) (но тогда придётся ESP32 из R4sGate обратно в ESPHome шить) и в [Home Assistant Xiaomi BLE integration](https://www.home-assistant.io/integrations/xiaomi_ble/) (но это нужен правильный BT свисток воткнутый в Home Assistant, а он будет мешать Zigbee)

**Comment by alutov** [comment]
Ну так поддержка этих датчиков и не заявлена. Возможно его можно прошить кастомной прошивкой, и тогда он увидится шлюзом. Изначально шлюзом только кастом и поддерживался, пока сяоми в сенсорах LYWSD03MMC не поправило прошивку и кастом туда перестал залезать. И, похоже, проблема эта не скоро решится. Потому и добавил поддержку оригинала на LYWSD03MMC. Ну и по мелочи еще некоторые сенсоры, на которые нет кастомных прошивок.
