### ISSUE TITLE
REDMOND SkyTracker 08S

### ISSUE THREAD

**Issue by DivanX10** [alutov/ESP32-R4sGate-for-Redmond#19]
Получится ли добавить данный трекер в прошивку? Данный трекер обнаруживается ESP32.
https://redmond.company/ru/products/sky-home/umnyy-treker-redmond-skytracker-08s/

**Comment by DivanX10** [comment]
Нашел отличную [прошивку](https://github.com/shogunxam/ESP32_BLETracker) для работы с трекером REDMOND SkyTracker 08S. Данный трекер REDMOND SkyTracker 08S прекрасно работает с этой прошивкой.
![treker](https://user-images.githubusercontent.com/64090632/101277507-f85f1d00-37c5-11eb-914b-5b76ad653268.jpg)

Получится ли это добавить в шлюз Redmond?

**Comment by alutov** [comment]
Если есть готовые решения, то пока не в приоритете. Ну может быть, если трекер мне понравится.

**Comment by ViktuK359** [comment]
Вот было бы отлично, добавить в прошивку штатную функцию ESPhome как ESP32 Bluetooth Low Energy Tracker Hub ))

**Comment by alutov** [comment]
REDMOND SkyTracker 08S виден в BLE мониторе.
