### ISSUE TITLE
Rs G210S не устанавливается соединение 

### ISSUE THREAD

**Issue by bar2104y** [alutov/ESP32-R4sGate-for-Redmond#190]
Чайник ищется BLE монитором, имею и Mac, и имя. Имя почему то RFS-KKL002, но чайник RK G210S.

Пробовал и по имени, и по Mac и с включённой, и с включённой use Mac in BLE auth, с режимами RS200S и 240S, ничего не помогает

В какую сторону можно попытаться поискать проблему? Возможно, что дело в отсутствии брокера? 

 ![Screenshot_20240111_224619.jpg](https://github.com/alutov/ESP32-R4sGate-for-Redmond/assets/33576679/588832c8-d968-4769-bde1-695049fc9dfe)
![Screenshot_20240111_224440.jpg](https://github.com/alutov/ESP32-R4sGate-for-Redmond/assets/33576679/cf05b421-0dc6-49f2-b4a8-04705dc936bd)

**Comment by alutov** [comment]
К сожалению, картинки ничего не показывают. В мониторе то он есть, нужно скопировать оттуда мак прямо с точками и далее смотреть Ble activity. Сейчас там Scanning, если появляется Open с именем и маком чайника, значит его мак в настройках введен верно. Если же этой строки нет - ощибка в настройках.  Нужно ввести скопированный мак адрес в поле имени/мака в нвстройках. Далее, если потом появляется Auth с именем и маком, после чего опять появляется Scanning, значит чайник не привязан к шлюзу. Нажимаем кнопку питания и держим до звукового сигнала, Привязка так и в родносм приложении. Брокер на соединение шлюза с чайником никак не влияет.

**Comment by bar2104y** [comment]
Хм, сделал все ещё раз, как Вы написали, и действительно заработало. Не могу найти отличий от того, то делал вчера, видимо просто где-то опечатка была.

В любом случае спасибо за проект!

Ps для RK G210S подходит как режим как RK G200s, так и RK G240s
