### ISSUE TITLE
Update failed. Rebooting...

### ISSUE THREAD

**Issue by vorlocsev** [alutov/ESP32-R4sGate-for-Redmond#20]
При попытке обновиться через wi-fi с 2020.12.09 на 2020.12.11 с помощью r4sGate.bin

**Comment by vorlocsev** [comment]
мешал включенный adguard. Обновилось.

**Comment by alutov** [comment]
Иногда бывает, что во время обновления esp рестартует, и обновляется не с первого раза. С чем связано, не знаю.
