### ISSUE TITLE
подключение к Yandex Home 

### ISSUE THREAD

**Issue by mut4b0r** [alutov/ESP32-R4sGate-for-Redmond#209]
Доброго времени суток, возможно не только у меня возникает данный вопрос:
Есть какой-то гайд по подключению r4sGate0 к умному дому от Яндекса, без прослоек в виде Home Assistant + Yandex Smart Home?
Кейс: есть кофеварка Redmond RCM-M1509S, Яндекс Станция, микротик и esp32. Задача - подключить кофеварку к Алисе только при помощи esp32

**Comment by alutov** [comment]
Сам так не пробовал, ничего посоветовать не смогу.
