### ISSUE TITLE
Возможно ли отключить светодиод на плате, постоянно горит при подаче питания, может тумблер есть какой в настройках? (плата ESP-WROOM-32) 

### ISSUE THREAD

**Issue by MikhailDeveloper** [alutov/ESP32-R4sGate-for-Redmond#210]

**Comment by alutov** [comment]
Я не специалист по платам esp32. Скорее всего светодиод подключен прямо на 3.3 вольта, через токоограничивающий резистор, разумеется. В шлюзе есть возможность настроить пины на выход с высоким или низким уровнем по умолчанию.
