### ISSUE TITLE
Support for mclh-09

### ISSUE THREAD

**Issue by bearklake** [alutov/ESP32-R4sGate-for-Redmond#211]
Can you add support for flower sensor mclh-09 in ble monitor. Examples:
https://github.com/devbis/ble2mqtt/blob/main/ble2mqtt/devices/flower_mclh09.py
https://github.com/dvb6666/esphome-components/tree/main/components/mclh_09_gateway

**Comment by alutov** [comment]
As far as I know, these sensors do not transmit useful data in the advertising messages. So far, I have not planned to add sensors that work only in connection mode.
