### ISSUE TITLE
Отправка топиков в Telegram WQTT

### ISSUE THREAD

**Issue by MikhailDeveloper** [alutov/ESP32-R4sGate-for-Redmond#212]
Здравствуйте, необходимо что бы после того как чайник вскипел отправлять на сервер wqtt, топик /telegram с текстом: Чайник вскипел. Далее сервер сам сформирует отправку сообщения в телеграмм, скажите как я могу сам создавать топики и отправлять их?

**Comment by alutov** [comment]
Все это легко реализуется сервером умного дома. Например, выключение чайника при температуре 100 градусов и есть событие "чайник вскипел".
