### ISSUE TITLE
не работает WI FI при смене сети

### ISSUE THREAD

**Issue by outsiderz** [alutov/ESP32-R4sGate-for-Redmond#24]
при вводе поключения к другой сети отличной от r4s не работает, возможно хотяб сделать пароль для стандартной сети r4s сделать по сложнее?

**Comment by alutov** [comment]
Может лучше понять, почему не работает подключение к сети с другим именем? Рекомендации стандартные: имя сети английскими буквами без спецсимволов и режим сети WPA2. У меня есп32 работает и с WPA3. Больше добавить нечего, уже [пробовал](https://github.com/alutov/ESP32-R4sGate-for-Redmond/issues/18).
