### ISSUE TITLE
Поддержка духового шкафа RO-5707S

### ISSUE THREAD

**Issue by enigmaspb** [alutov/ESP32-R4sGate-for-Redmond#29]
Подскажите как вам помочь добавить поддержку данной печки в вашем гейте ?
Какие нужны для этого логи и данные ?

**Comment by alutov** [comment]
Можно, но только нужен лог команд и ответов. Если коротко, нужно включить в смартфоне в опциях разработчика лог блютуса, соединиться с печкой и пробежаться по командам. Потом слить лог и далее с ним разбираться. Если будет этот лог, то можно будет добавить печку.

**Comment by enigmaspb** [comment]
Сделал лог пробежавшись по всем пунктам меню и включая-выключая режимы  . 
Большое вам спасибо за вашу работу .

[btsnoop_hci.log](https://github.com/alutov/ESP32-R4sGate-for-Redmond/files/6014175/btsnoop_hci.log)

![menu_1](https://user-images.githubusercontent.com/1804979/108584926-28927280-7356-11eb-8523-b858a847d475.jpg)
![menu_2](https://user-images.githubusercontent.com/1804979/108584928-2af4cc80-7356-11eb-8bb1-0052d6466ad1.jpg)

**Comment by alutov** [comment]
Это тот лог? Я не нахожу данных, только репорты сканирования устройств(advertising reports). Хотя печка мелькает. Чтобы не засорять ветку, можно перейти в telegram. (@alutov).

**Comment by enigmaspb** [comment]
Извините давно вам не писал 
пока тот функционал что сделали работает , вот пришла новая ESP с антеной ,  сделал даже экран . 
Правда девушка просит больше информации на экране 

![image](https://user-images.githubusercontent.com/1804979/119257375-b6882e80-bbcd-11eb-8e04-c0a089a765c1.png)
