### ISSUE TITLE
Можно ли добавить топик MQTT с состоянием подсветки?

### ISSUE THREAD

**Issue by panferovaleksey** [alutov/ESP32-R4sGate-for-Redmond#3]
Вкл./выкл., а в идеале если это возможно цвет текущий RGB

**Comment by alutov** [comment]
Я не знаю, отдает ли чайник состояние подсветки. И есть команда только на включение подсветки, выключается общей командой выключения. А потому большого смысла не вижу. Цвет показывает, но опять же не из чайника, а из шлюза. Чтобы видеть, что команда прошла и цвет поменялся.

**Comment by alutov** [comment]
Состояние сделано.

**Comment by alutov** [comment]
Состояние вкл/выкл берется из чайника. Текущий цвет пока берется из самого шлюза. Постоянно делать отдельный запрос на цвет не хочется.
