### ISSUE TITLE
Образ Docker

### ISSUE THREAD

**Issue by Drafteed** [alutov/ESP32-R4sGate-for-Redmond#30]
Добрый день!
Не планируете оформить разработку в виде Docker образа для, например, Raspberry? По типу zigbee2mqtt. Даже название могу предложить: redmond2mqtt или r4s2mqtt :) 
Было бы очень здорово!

**Comment by alutov** [comment]
Не планирую ибо не имею возможности. Пока освоил только есп.  Для ХА существует интеграция с использованием ble, как раз подойдет для малинки и ей подобных.
