### ISSUE TITLE
RK-M216S-E kettle

### ISSUE THREAD

**Issue by mbatorowicz** [alutov/ESP32-R4sGate-for-Redmond#33]
Привет,
есть шанс, что ворота поддерживают RK-M216S-E ?

**Comment by alutov** [comment]
Да.

**Comment by mbatorowicz** [comment]
На данный момент я не вижу эту модель в списке доступных.
Будет ли обновление ПО?
Надо ли самому что-то переделывать?

**Comment by alutov** [comment]
Как правило, протокол всех современных моделей чайников Redmond совпадает. Можно выбрать в шлюзе 200 или 240 чайник. Это один и тот же протокол, просто взята нижняя и верхняя модель. Всех поддерживаемых моделей в списке никогда не будет - это никому не нужное расходование ресурсов esp32.

**Comment by mbatorowicz** [comment]
Не знаю, как подключить чайник. У меня есть чайник RK-M216S-E. В настройках выбрал RK-G200S. Чайник не рвется. Какая процедура подключения?

**Comment by alutov** [comment]
Почитайте для начала главную страничку, там все написано.

**Comment by mbatorowicz** [comment]
Мне кажется, что я следую инструкции. Я снял фильм.
https://youtu.be/INdXLsM7BVY

**Comment by alutov** [comment]
Шлюз ищет чайник по имени. Вбили произвольное имя. У вас это "czajnik". Это поле должно быть не пустое, иначе скан не запустится. Выбираете сразу 200 или 240 тип. Дальше перегружаете шлюз. Он показывает имя чайника в строке "BLE last found device name".  Копируем(Ctrl-C)  это имя затем идем в Setting и вставляем это имя (Ctrl-V) в поле "Name". Туда, где на видео вписан "czajnik". Сохраняете еще раз. Шлюз перегрузится и только после этого зажимаете и держите кнопку на чайнике.)

**Comment by mbatorowicz** [comment]
Спасибо большое - сработало

**Comment by mbatorowicz** [comment]
Есть еще одна проблема. Шлюз не может подключиться к серверу MQTT. Все данные обязательно введены правильно: адрес, порт, логин, пароль. У меня есть брокер Mosquitto в Home Assistant. Остальные устройства подключаются без проблем.

**Comment by alutov** [comment]
Может в пароле ошибка и хром что-то свое поставил. Остальное видно в установках. Либо шлюз и брокер в разных сетях и они не видят друг друга. Можно с компьютера, где крутится брокер дать пинг на шлюз. Может какое шифрование, я там сильно не вникал, но пока это первый случай проблем с мктт брокером.  Я для тестов, в том числе мктт дискавери, держу на 3 малинке ХА с москитто. Ставил все по умолчанию, и шлюз нормально дружит с москитто.

**Comment by mbatorowicz** [comment]
У меня все время проблема с MQTT. Я сделал новый чистый домашний помощник и Mosquito, но он все равно не подключается, когда установлен пароль. Когда я разрешаю подключения без пароля, он подключится. У меня есть # в моем пароле, если это может повлиять на связывание.
Другая проблема заключается в том, что шлюз не отправляет ничего после mqtt. Я использую MQTT Explorer, и он ничего не видит. MQTT.fx тоже ничего не видит.

**Comment by alutov** [comment]
Проблема именно в символе "#" в пароле. Вот лог с паролем "esp#":
I (4189) R4S: Mqtt url: mqtt://esp:esp#@192.168.1.10:1883
E (4199) MQTT_CLIENT: Error parse uri = mqtt://esp:esp#@192.168.1.10:1883
W (4199) MQTT_CLIENT: Client asked to stop, but was not started
E (4209) MQTT_CLIENT: Client was not initialized
Помочь не смогу, так как этот символ в  url не принимает сама библиотека Mqtt. Проще его убрать из пароля.

**Comment by mbatorowicz** [comment]
Наконец-то это сработало. Спасибо за вашу помощь и терпение.

**Comment by m4rlb0r0** [comment]
сотни попыток, и я не могу подключиться ... пожалуйста, дайте мне подсказку!

![C90FC937-EFFF-43A4-83E9-AC9053CC8016](https://user-images.githubusercontent.com/38866859/111848592-b0df4580-890b-11eb-8548-866b1f27fe30.png)

**Comment by alutov** [comment]
А что стоит в Setting?  Должно быть так:  Name RK-M216S-E (эту строчку лучше скопировать из "BLE last found device name"), тип RK-G200S или RK-G240S. И потом зажать "+" на чайнике до соединения.

**Comment by m4rlb0r0** [comment]
![Uploading 68E9C3CB-A37A-4702-BA2F-03BA11A47F3F.png…]()

**Comment by m4rlb0r0** [comment]
![EF7F5893-5168-4A95-8DDF-05BAFAA12226](https://user-images.githubusercontent.com/38866859/111867245-0e5aad00-8973-11eb-9cef-39ed590d22fd.png)

Скопировал, добавил и зажал кнопку и ничего. Я собираюсь записать видео сегодня вечером

**Comment by m4rlb0r0** [comment]
https://youtu.be/ORNd3WLphas

**Comment by m4rlb0r0** [comment]
как долго нужно удерживать эту кнопку?

**Comment by alutov** [comment]
Либо до соединения, либо как пискнет сразу отпустить. Помнится, на чайнике у меня проходил первый вариант, на розетке только второй. У розетки, правда, звука нет, как начнет мигать нужно отпускать кнопку.

**Comment by m4rlb0r0** [comment]
для сопряжения этой модели нужно удерживать кнопку включения нет +

оно работает ! большое спасибо !
