### ISSUE TITLE
Отвал BLE

### ISSUE THREAD

**Issue by exotsk** [alutov/ESP32-R4sGate-for-Redmond#37]
Андрей, поставил от 8.03. с  IDF v4.4-dev-4-g73db14240, стабильный отвал BLE раз в сутки. Одновременно улучшил качество wifi. не помогло.
Ребут досочки помогает. Может сделать "ночные ребуты" по расписанию ?

**Comment by alutov** [comment]
У меня пока все нормально. Wifi правил в 9.03.2020. Если отвалы остались, придется поставить птичку в  "BLE monitoring".

**Comment by exotsk** [comment]
Понял тебя. Я сегодня 9.03 поставил. Пока сутки не прошли. Отпишусь.

**Comment by alutov** [comment]
А сколько устройств определено и подключено? У меня 3 и 2 на одном, 2 и 2 на другом. То есть скан постоянно не бегает, все соединилось и скан остановился. Может в этом дело.

**Comment by exotsk** [comment]
1 устройство. 201 чайник, есть еще мультиварка но она кардинально не совпадает с твоей :) 
Только что залипла предыдущая версия с галкой BLE monitoring
сейчас поставлю  2021.03.14. 
скажи как лог снять, сделаю. Если уарт слушать, то на таком удалении у меня не получится. чайник далеко от компа.

**Comment by alutov** [comment]
Пока ничего не нужео. Нашли один баг в новой в4рсии. Может поможет. И добавил строку состояния скана, видна до соединения.

**Comment by exotsk** [comment]
По кинетикам, второй шлюз стоить в паре метров по за стеной. Знаю о том что можно указывать точку в меше, установил принудительно ближнего. Мультиварка SkyCooker M223S

**Comment by exotsk** [comment]
Андрей, последняя версия похуже будет в стабильности, 2 суток подряд отвалы.
![image](https://user-images.githubusercontent.com/54969124/113653547-4591c380-96c0-11eb-94ab-efb5918011ae.png)

**Comment by alutov** [comment]
Версия от 25.03? В чем проблема, зависание бле, перезагрузка? Что показывает ble activity, scanning, idle? Пока жалоб на отвал бле не было. У меня 9 суток аптайм без отвалов, причем ble monitoring выключен. Код в последних версиях я не менял, только опции сборки.

**Comment by exotsk** [comment]
значит так совпало. Но галка стоит, чайник на базе, чайника не видит. Самая последняя, которая выложена сейчас. сейчас сутки вроде норм
