### ISSUE TITLE
Температура 35

### ISSUE THREAD

**Issue by dmatora** [alutov/ESP32-R4sGate-for-Redmond#38]
Купил чайник Redmond (в основном чтобы греть воду до 35 градусов)
В приложении ReadyForSky такая возможность есть, а вот в R4sGate все что меньше 40 - отключает подогрев
Нельзя ли добавить поддержку низких температур?

**Comment by alutov** [comment]
Какая минимальная температура подогрева в этом чайнике?

**Comment by dmatora** [comment]
35
![image](https://user-images.githubusercontent.com/647062/111031544-1d90a680-8419-11eb-9cb0-492cc3a8e091.png)

**Comment by alutov** [comment]
Сделал минимум 30 по mqtt, только для редмонда. Xiaomi забросили? Я только на днях обнаружил, что в нем keep warm перезапускается только один раз...

**Comment by dmatora** [comment]
Xiaomi так и не удалось решить проблему с потерей контроля при остывании воды. У меня 2 xiaomi чайника, под разные задачи, без удаленного управления сильно не страдал. 
Redmond купил только когда стала нужна вода 35 градусов, плюс долго мониторил когда на Авито хорошая цена подвернется (взял новый за 2000р)

**Comment by alutov** [comment]
Наверное там таки 20 градусов предел. Все же хочу добить хотя бы бессрочный keep warm.

**Comment by dmatora** [comment]
У меня ниже 30 (если не 40) контроль теряется вроде

**Comment by dmatora** [comment]
В помещении у меня не ниже 20

**Comment by dmatora** [comment]
> Сделал минимум 30 по mqtt, только для редмонда. Xiaomi забросили? Я только на днях обнаружил, что в нем keep warm перезапускается только один раз...

Попытался обновить прошивку через веб, не получилось.
Накатил через flasher, 35 градусов работает, спасибо.
