### ISSUE TITLE
Стоит явно упомянуть ограничение на длину пароля MQTT

### ISSUE THREAD

**Issue by strannick-ru** [alutov/ESP32-R4sGate-for-Redmond#39]
При попытке ввести пароль на 16 символов (у меня как раз такой использовался), он не сохраняется после перезагрузки и соединения с MQTT-брокером не происходит.

Если уменьшить длину пароля  всё ок.

Выяснил, что причина именно в этом не сразу  : )
Думаю, стоит задокументировать это.

**Comment by alutov** [comment]
Есть такое, длина 15 символов, вайфая 63. Не лумал, что в локалке сильно будут шифроваться)))

**Comment by alexreddy78** [comment]
Добрый день!

Никак не поправить? Уж очень не хочется в MQTT пароль менять и везде потом его переделывать.

Спасибо

**Comment by alutov** [comment]
И какая длина пароля нужна?

**Comment by alexreddy78** [comment]
> И какая длина пароля нужна?

Добрый день, Андрей!

Ну хотелось бы 18 символов :)

С Уважением

**Comment by alutov** [comment]
Сделал 19 символов.

**Comment by alexreddy78** [comment]
@alutov Благодарю! Думаю автор issue должен закрыть его :) @strannick-ru
