### ISSUE TITLE
Добавление поддержки других SPI TFT дисплеев

### ISSUE THREAD

**Issue by vorlocsev** [alutov/ESP32-R4sGate-for-Redmond#44]
Здравствуте!
Возможно ли добавить поддержку других дисплекв( ili 9488, ili9373 и т.д.)
Столкнулся с проблемой добавления ili9488, пытался поправить код, но оказаломь слишком сложно для меня)) напрямую bodmer драйверы не добавляются, а сильно интегрированы в код tft.

**Comment by alutov** [comment]
Микросхема ili9341 используется почти везде на разрешении 320*200, в том числе в уже готовых устройствах, пригодных для шлюза. Добавить другие драйверы можно, конечно, только вот смысла я не вижу. Дело тут не в микросхеме, а в разрешении экрана. Если принимать jpeg картинку из сети, ее нужно где-то хранить до распаковки. У меня jpeg картинка 320*200 занимала примерно 20кб. Буфер 32кб еще найти получается, а вот при увеличении разрешения вдвое размер растет уже в 4 раза, и памяти esp32 уже тупо не хватает.
