### ISSUE TITLE
Rs170S

### ISSUE THREAD

**Issue by robertbigk** [alutov/ESP32-R4sGate-for-Redmond#45]
Hi I add Redmond SkyKettle RK-M170S-E

![archival-redmond-skykettle-rk-m170s-e-czarny,24403058185_3](https://user-images.githubusercontent.com/34956477/123101068-f7c16780-d433-11eb-9902-9d3125b91269.jpg)

Kettle detected and work switch on/off

![XYwHmNhfC9](https://user-images.githubusercontent.com/34956477/123101314-3525f500-d434-11eb-9380-49596ea01e25.png)
Kattle  have multiple temperature setup 40 ,55,70,80,95

![msedge_z10CAH2nJg](https://user-images.githubusercontent.com/34956477/123101770-aa91c580-d434-11eb-886a-ed9504152ba3.png)

when I try setup temperature I set 55 and the function goes off.

only work switch on go heat for 100. How to add to Ha's missing functionality?

Kettle very silimar for 173s  multistep temperature. Coud You help me?

**Comment by alutov** [comment]
It may be that in this model the protocol differs from the same 173 teapot. I saw something similar on the majordomo. If the native android r4s application can set only a few temperature values, and not any in the range of 30-90, then it is so.

**Comment by robertbigk** [comment]
Thx for the answer ok then possible to create entities or other way option to setup this couple level o temperature?
40,55,70,85 and 95? Or only way I have option heat or no heat and that it?:)

**Comment by alutov** [comment]
Upload "r4sGate170.bin" from "build" folder, select rk-m170s and test it in all modes (web and mqtt).

**Comment by robertbigk** [comment]
Supert Work!!! Spasiba Balszoje:) 

![msedge_zJkgUpsR15](https://user-images.githubusercontent.com/34956477/123512490-115aed00-d688-11eb-996a-fabb438f021b.png)

First show current temperature befoure that not work .

Second is jumping to step what got kettle i choise 20 his jump to 1 set of temperature 40 i choise 45 jump to 55. I perfect big thanks for help
