### ISSUE TITLE
Не подключается к WiFI

### ISSUE THREAD

**Issue by Drafteed** [alutov/ESP32-R4sGate-for-Redmond#51]
Доброго времени суток!

Ни в какую не подключается к основной сети. Пробовал и прошивку от 3-го месяца и текущую. ERASE ESP делал.
Сеть разумеется 2.4Ghz, 5Ghz висит на другом названии. Сеть у меня называется WiFi Draft, т.е. имеется пробел  Может из-за этого? В интерфейсе после сохранения настроек название сети меняется на: WiFi+Draft. Пароль обычный, цифровой, без спец. символов.

**Comment by Drafteed** [comment]
Ну да, переименовал сеть без пробелов - подключилось. Есть возможность пофиксить?

**Comment by alutov** [comment]
Поправил.

**Comment by Drafteed** [comment]
Спасибо!
