### ISSUE TITLE
Статистика

### ISSUE THREAD

**Issue by Drafteed** [alutov/ESP32-R4sGate-for-Redmond#52]
Простите, что снова тревожу.. Просто перешел с кастомной интеграции для HA на вашу прошивку, настраиваюсь  :) 

В предыдущей версии кастомного компонента (которую я использовал) для RK-G210S была статистика включений и количество потребленной энергии. [Тут можно глянуть как его получить](https://github.com/mavrikkk/ha_kettler/blob/217e5088ba75329b2b416b795fd73ba047db8b7e/custom_components/r4s_kettler/__init__.py#L242). Возможно это реализовать?

**Comment by alutov** [comment]
Подумаю. И куда это все выводить?

**Comment by Drafteed** [comment]
Отсылать в mqtt, как rssi :)

**Comment by Drafteed** [comment]
В компоненте эти данные запрашивались с каждым обновлением (~15/30сек). Думаю чтобы не грузить эфир лишними запросами, ее можно запрашивать например раз в 15-30 минут.

**Comment by Drafteed** [comment]
И еще добавлю сюда, чтобы отдельный не открывать:

При снятии чайника с подставки в HA постоянно вылетает ошибка:
```Logger: homeassistant.components.mqtt.climate
Source: components/mqtt/climate.py:480
Integration: MQTT (documentation, issues)
First occurred: 0:27:36 (18 occurrences)
Last logged: 14:30:10

Invalid modes mode: offline```

**Comment by alutov** [comment]
Добавил статистику.

**Comment by Drafteed** [comment]
Очень круто! Спасибо за фикс с режимом и новые переключатели. 
А с каким интервалом статистика обновляется? Уже два часа после обновления, включил его раз 5, но пока так и не прилетело )

<img src="https://user-images.githubusercontent.com/11841379/137590469-c4daa2a4-be8a-4b11-8874-0a7a510f0080.png" width="300">

**Comment by Drafteed** [comment]
А хотя в брокере данные видно, что-то не так с дискавери.

<img src="https://user-images.githubusercontent.com/11841379/137590821-a45061f1-99c6-4e83-864d-54bef342d042.png" width="400">

**Comment by alutov** [comment]
Да, есть такое. Я тестировал на совмещенных топиках. Поправил.

**Comment by Drafteed** [comment]
Большое Вам спасибо! Теперь все просто замечательно :)
