### ISSUE TITLE
Move project to ESPHOME

### ISSUE THREAD

**Issue by MrC0nst** [alutov/ESP32-R4sGate-for-Redmond#54]
#feature request
Is it possible to move this project to ESPHOME engine?

**Comment by didjeru** [comment]
I support this proposal!

**Comment by sfxdxTeam** [comment]
I support this proposal!

**Comment by Alexamig** [comment]
I fully support it!

**Comment by KomX** [comment]
I fully support it!

**Comment by tayanov** [comment]
+1

**Comment by Mantikor** [comment]
+1

**Comment by vmakeev** [comment]
+1

**Comment by alutov** [comment]
Куда портировать то? Они сами портируются: https://github.com/esphome/feature-requests/issues/1414

**Comment by uefik** [comment]
Было бы круто!
