### ISSUE TITLE
Поддержка мультиварки RMC-M961S

### ISSUE THREAD

**Issue by Timoxa1329** [alutov/ESP32-R4sGate-for-Redmond#56]
Будет ли добавлена поддержка мультиварки RMC-M961S?

**Comment by alutov** [comment]
Можно попробовать подключить мультиварку в режиме 903. Если получится, тогда нужно только поправить список программ. Если же не получится, нужно снимать лог общения мультиварки и родного приложения.

**Comment by Timoxa1329** [comment]
День добрый. Подключить получается и оно работает. Действительно необходимо только слегка подправить список программ. Премного благодарен за помощь

**Comment by alutov** [comment]
Напишите, какие программы 903 соответствуют каким в 961. И желательно нужную температуру и время каждой программы 961.

**Comment by Timoxa1329** [comment]
903 - 961
Multicooker - Рис/крупы, 10 мин, 100 °C
Milk_porridge - Жарка, 15 мин, 150 °C
Stewing - На пару, 25 мин, 100 °C
Frying - Выпечка, 1 час, 140 °C
Soup - Тушение, 1 час, 100 °C
Steam - Мультиповар, 30 мин, 100 °C
Pasta - Плов, 1 час, 110 °C
Slow_cooking - Суп, 1 час, 100 °C
Hot - Молочная каша, 30 мин, 100 °C
Baking - Йогурт, 8 часов, 40 °C

**Comment by alutov** [comment]
Добавил, можно пробовать.
