### ISSUE TITLE
смена домена на water heater

### ISSUE THREAD

**Issue by MaxWh1t3** [alutov/ESP32-R4sGate-for-Redmond#58]
Не знал куда написать, простите. Зачем выбран домен климат, когда есть прекрасный water_heater? И например water_heater.kettle прекрасно себя в нем чувствует, по крайне мере интеграция от https://github.com/mavrikkk/ha_kettler туда его и определяет, что довольно удобно. Но в той интеграции чайник постоянно отваливается, пропускает команды и прочее, поэтому решил попробовать вашу и через 20 мин у меня еще больше выбор управления параметрами, даже энергию считает) Но не помешала бы более подробная статья по настройкам или хотя бы пояснения, т.к. не все очевидно...

**Comment by alutov** [comment]
Нет пока в Mqtt Discovery сущности water_heater. Будет - переделаю, это быстро. Тем более, сам сейчас решил переехать на ХА, и потому заинтересован. По статье, как что смог уже написал, подробнее есть статьи, быстро ссылку не дать не смогу, нужно их поискать в инете.

**Comment by MaxWh1t3** [comment]
спасибо!
про статью это к тому, что мне не пришлось всякие топики и прочее прописывать- все само пробросилось, очень удобно! ну и разбиение на абзацы не помешает, а то немного в кучу как-то.

**Comment by MaxWh1t3** [comment]
Спасибо! Но пока и так удобно вполне)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

чт, 23 дек. 2021 г. в 12:40, Andrey Lutov ***@***.***>:
