### ISSUE TITLE
длинный пароль для брокера mqtt

### ISSUE THREAD

**Issue by yack1** [alutov/ESP32-R4sGate-for-Redmond#59]
при попытке ввести пароль для входа в MQTT конфигурация "pahnu1ahSied8voofaer8teenaeGh7ohchie5vee2Io4phae3Ji2aithahquad2f" не может быть сохранена

**Comment by alutov** [comment]
Длина пароля 19 символов. Не понимаю, зачем пароли такой длины. Прошивка предназначена для работы с локальным Mqtt сервером в локальной сети и увеличение длины пароля пока не планируется.
