### ISSUE TITLE
Обновление прошивки

### ISSUE THREAD

**Issue by RavenHuginn** [alutov/ESP32-R4sGate-for-Redmond#60]
Здравствуйте.
Подскажите есть настроенных шлюз, при обновлении через web настройки сохраняются или нужно будет заново настроить шлюз?

**Comment by alutov** [comment]
Все сохраняется.

**Comment by Drafteed** [comment]
Почему-то при обновлении через веб, браузер выкидывает CONNECTION_RESET.

**Comment by alutov** [comment]
Обновление проверял на едже, хроме и файфоксе. Возможно, плохой уровень вайфая. Или же в есп старая версия, в которой при обновлении не закрываются все бле соединения.

**Comment by Drafteed** [comment]
Очень интересно - с винды обновляется. В маке, в любом браузере (проверил Safari, FF, Chrome) нет.

**Comment by alutov** [comment]
Как раз предсказуемо. Дело в том, что у разных браузеров приходящие на есп заголовки при обновлении немного отличаются. Задача отрезать заголовок и писать только данные. Где-то может что-то не учел ввиду отсутствия у меня информацмм.

**Comment by Drafteed** [comment]
@alutov 

Вот что улетает вместе с файлом:

``` 
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: ru,en-US;q=0.9,en;q=0.8,ru-RU;q=0.7,zh-TW;q=0.6,zh;q=0.5
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 1587194
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarye7P6hVQ3fslBtuMk
DNT: 1
Host: 192.168.1.11
Origin: http://192.168.1.11
Pragma: no-cache
Referer: http://192.168.1.11/update
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
```

**Comment by alutov** [comment]
Если есть возможность, загрузите последнюю версию, а потом запишите лог esp32 при попытке обновления из mac os. Там дожен записаться post заголовок.

**Comment by alutov** [comment]
Поправил обновление для macos/ios.
