### ISSUE TITLE
Конвектор REDMOND SkyHeat 7001S

### ISSUE THREAD

**Issue by Su4oNoK** [alutov/ESP32-R4sGate-for-Redmond#63]
Можно ли добавить новое устройство конвектор REDMOND SkyHeat 7001S ? 
Сейчас пробую управлять им как SkyPort 103S, но во первых нет возможности выбирать режим мощности 25/50/75/100 
А во вторых, пока не нашел причину, но если выставить режим физической кнопкой на самом обогреватели, он отключается от ESP и висит там в оффлайн статусе, а потом становится Power RCH-7001S not connected.
Буду благодарен если поможете решить проблему.

**Comment by alutov** [comment]
Чтобы добавить регулирование мощности, нужно снять лог блютуса в телефоне вовремя работы программы и выбора режимов. Что касается отключения, сказать ничего не могу, такого прибора не видел. Если же брать розетку, то там долгое нажатие на кнопку вводит розетку в режим сопряжения, а если продолжать держать кнопку, то в конце концов розетка забывает все подключения. Может что-то подобное происходит и с нагревателем.

**Comment by Su4oNoK** [comment]
С подключением - зажал кнопку сопряжения секунд на 20, как я понял устройство всех забыло. Повторно прицепил к esp пока вроде норм, буду наблюдать. 

Вопрос со снятием лога - есть гайд как это правильно сделать?

**Comment by alutov** [comment]
Лог уже прислали, конвектор RCH-7001S добавлен. Возможно, он совместим и с другими конвекторами редмонда, в частности с RCH-4529S.

**Comment by artt652** [comment]
Точно будут работать конвекторы RCH-7002S, RCH-7003S, платы управления у них с RCH-7001S одинаковые, различия только в длине и мощности нагревательного элемента.

**Comment by alutov** [comment]
Ага, спасибо, отмечу это в описании.

**Comment by Su4oNoK** [comment]
Всё работает, огромное спасибо!
