### ISSUE TITLE
 Поддержка мультиварки RMC-M40S

### ISSUE THREAD

**Issue by enigmaspb** [alutov/ESP32-R4sGate-for-Redmond#87]
Подскажите какую самую близкую лучше всего выставить для теста ?

**Comment by alutov** [comment]
Я не знаю, пробуйте 903, 92 или же 800, какая модель будет правильно отображать состояние. Думаю, что список программ вряд ли совпадет, так что лучше выложить список программ в том же телеграме с тем же логином, что и здесь, сделаем 40 модель.

**Comment by Psytoshgen** [comment]
Здравствуйте,  чтобы не плодить топиков, возможно ли старушку мультиварку добавить? RMC-M223S

COOKER_PROGRAMS = {
'Рис':['01', '00', '64', '00', '23','00','00','01'],
'Томление':['02', '00', '61', '03', '00','00','00','01'],
'Плов':['03', '00', '6e', '01', '00','00','00','01'],
'Жареные_овощи':['04', '01', 'b4', '00', '12','00','00','01'],
'Жареная_рыба':['04', '02', 'b4', '00', '0c','00','00','01'],
'Жареное_мясо':['04', '03', 'b4', '00', '0f','00','00','01'],
'Тушеные_овощи':['05', '01', '64', '00', '28','00','00','01'],
'Тушеная_рыба':['05', '02', '64', '00', '23','00','00','01'],
'Тушеное_мясо':['05', '03', '64', '01', '00','00','00','01'],
'Паста':['06', '00', '64', '00', '08','00','00','01'],
'Молочная_каша':['07', '00', '5f', '00', '23','00','00','01'],
'Суп':['08', '00', '63', '01', '00','00','00','01'],
'Йогурт':['09', '00', '28', '08', '00','00','00','00'],
'Выпечка':['0a', '00', '91', '00', '2d','00','00','01'],
'Овощи_на_пару':['0b', '01', '64', '00', '1e','00','00','01'],
'Рыба_на_пару':['0b', '02', '64', '00', '19','00','00','01'],
'Мясо_на_пару':['0b', '03', '64', '00', '28','00','00','01'],
'Разогрев':['0c', '00', '64', '00', '28','00','00','01']}

Подключал через интеграцию Ble scanner
Для ключа использовал генератор - отсюда просто забил 8 символов и нажал сгенерировать HEX
https://crypt-online.ru/crypts/text2hex/

получил такое простое окошко в итоге, которое кроме включить програамму ничего толком не показывает.
![rmc](https://user-images.githubusercontent.com/94195788/174047031-0565b31d-92ce-481f-8784-57d4a42de153.jpg)

Прошу прощения если уже повторил что-то, но влез во всё это недавно - совсем профан.

**Comment by alutov** [comment]
А программы не совпадают с 224?

**Comment by Psytoshgen** [comment]
со шлюзом управился - роутер Xiaomi iot 2350 не дает в гостевой сети доступ ни на какие устройства. Решил через создание обычной сети r4s для первичной настройки. Подключил шлюз к MQTT, сбросил мультиварку.
Через BLE сканер нашел свою мультиварку, через приложение включил сопряжение со шлюзом через bluetooth и все остановилось на Connecting RMC-M223S (Auth).
Какие данные нужны для поддержки девайса?

**Comment by alutov** [comment]
Работает как 224? Тогда почему из веба не управляется.

**Comment by Psytoshgen** [comment]
> Работает как 224? Тогда почему из веба не управляется.
все управляется, но после ребута не всегда подключается.  подключилось с 4го ребута. (сейчас подключается каждый 2й ребут) пока экспериментировал с BLE монитором, так же заметил что интеграция BLE Monitor подхватывает датчики и девайсы сяоми сразу. ваша видит устройства, но с сопряжением немного не ясно.  есть bluetooth ночник сяоми и прошитый на pvvx гигротермометр пишет ATC_C45B57 (Auth / Id:1) тоже самое пишет yunmai color (либо auth / id:1, либо open) (весы, что потом стали весами Xiaomi yunmai color scale)
скрины прикладывю
![rmc](https://user-images.githubusercontent.com/94195788/174481986-c2da2d02-aabc-465e-8fbc-4aa13cf7e555.jpg)
![gate](https://user-images.githubusercontent.com/94195788/174481999-4539289d-8809-4789-a676-4e9027f635bc.jpg)
![device](https://user-images.githubusercontent.com/94195788/174482012-46e43f08-a2a5-4ab9-b7d2-312be6823a95.jpg)
на деле ваш компонент работает в разы лучше Ble monitor, просто есть немного не решенных вопросов, которые решаются экспериментами в настройках. например, как организовать 10 ble учтройств, когда полей всего 3

**Comment by alutov** [comment]
Все термометры заводятся через ble monitor. Просто нужно там найти интересующий термометр и в поле timeout ввести значение примерно 120-180 с и нажать ок. После чего термометр прокидывается в ХА. Весы пока что не поддерживаются. Что касается коннекта полсе ребута, можно и разобраться, но желательно снять лог с есп32.

**Comment by Psytoshgen** [comment]
Здравствуйте, завалил всю систему и только заново поднял. По логам не скажу, но заметил что мультиварка не сразу подхватывается, если просто стоит. Если что-то готовится - проблем нет.  В целом можно смело утверждать, что ваш компонент полностью поддерживает данную модель. Спасибо.
