### ISSUE TITLE
Redmond SkyBaker

### ISSUE THREAD

**Issue by dmamontov** [alutov/ESP32-R4sGate-for-Redmond#9]
Интересно, есть ли шанс подключить redmond skybaker? может есть у кого инструкция на разбор протокола?

**Comment by alutov** [comment]
Есть конечно. Только протокола пока не встречал. И что это за устройство такое? Но можно снимать самому и потом разбираться. Сам это пока не делал, подсказать не могу.

**Comment by dmamontov** [comment]
> Есть конечно. Только протокола пока не встречал. И что это за устройство такое? Но можно снимать самому и потом разбираться. Сам это пока не делал, подсказать не могу.

Это мультипекарь. Походу придется самому снимать)

**Comment by alutov** [comment]
Пока у меня нет логов на это устройство. Будут логи, добавлю

**Comment by Villi342** [comment]
Спасибо, постараюсь собрать на этой неделе

**Comment by alutov** [comment]
Можно в телеграме, адрес есть на главной странице гита.

**Comment by Villi342** [comment]
Хорошо

**Comment by alutov** [comment]
Мультипекарь добавлен, но пока полностью не протестирован.
