### ISSUE TITLE
Поддержка MiBand

### ISSUE THREAD

**Issue by MrSnakeSPb** [alutov/ESP32-R4sGate-for-Redmond#91]
Здравствуйте. Спасибо вам за вашу классную разработку и ваш труд.
Хотел вас попросить сделать поддержку в BLE Monitor смарт-часов Xiaomi MiBand.
Это было бы здорово в качестве маяка-датчика присутствия использовать браслет.

**Comment by alutov** [comment]
Я пока не готов ответить, с браслетом не сталкивался. У него случайно не постоянный мак адрес?

**Comment by MrSnakeSPb** [comment]
Мак у него постоянный, можно посмотреть на самом устройстве. В программе связи стоит внешнее обнаружение, т.е. его могут увидеть другие устройства. Но Ble Monitor его не находит. Мне и не нужно проверять его активность. Мне сигнализацию было бы удобно им снимать) Пока wifi подвяжется и обновиться, сигнализация уже всех домочадцев уведомит о проникновении. Как в басне"Волки, Волки!!!" получается.

**Comment by alutov** [comment]
Он просто может не попадать в таблицу, если там все места заняты термометрами. Все же таблица маловата.(

**Comment by MrSnakeSPb** [comment]
> У меня четверка, тоже отлично видится в мониторе. Возможно у вас вокруг просто больше 10 bt-устройств, если да то попробуйте включить активный скан и унести подальше от других устройств шлюз и браслет. А когда увидит, выставите таймаут и вернёте пассивное сканирование.

Тоже четвертый мибанд. Соседский HONOR Band 5 и его чайник с телевизором видит, а мой телефон и браслет не видит. Попробую форматнуть и перепрошить, может новые в память уже не лезут.

**Comment by MrSnakeSPb** [comment]
В общем такая ситуация, после отключения блютуза на телефоне, браслет появляется и работает как надо, но стоит обратно его включить, то исчезает. Я так понимаю, это особенность работы мибанда (.
