### ISSUE TITLE
MQTT ssl

### ISSUE THREAD

**Issue by utya** [alutov/ESP32-R4sGate-for-Redmond#96]
Привет. Подскажите будет поддержка ssl/tls mqtt?

**Comment by alutov** [comment]
Пока не думал, а нужно? Для локального брокера вроде не критично.

**Comment by utya** [comment]
Да вот поднял в облаке настроил tls хотел всех уже туда перевести, но потом понял лучше наверно поднять локальный и забриджевать с внешним

**Comment by alutov** [comment]
Немного почитал об mqtt с ssl. Честно говоря, не очень хочется возиться с сертификатами. Но. Есть в москито вариант использовать PSK, и даже вариант с  авторизацией и шифрованием  PSK. Очень удобно, как по мне. Но вот поддержки этого в HA не нашел.

**Comment by utya** [comment]
> Немного почитал об mqtt с ssl. Честно говоря, не очень хочется возиться с сертификатами. Но. Есть в москито вариант использовать PSK, и даже вариант с авторизацией и шифрованием PSK. Очень удобно, как по мне. Но вот поддержки этого в HA не нашел.

ну не знаю, может будет полезно как у тасмота, они там двумя путями юзают, fingerprint и сашивают letsecrypt корневой сертификат

**Comment by utya** [comment]
https://tasmota.github.io/docs/TLS/

**Comment by alutov** [comment]
Ага, почитаю, спасибо.

**Comment by alutov** [comment]
Добавил ssl по стандартной схеме. Пробовал на локальном брокере и самоподисанными сертификатами.

**Comment by utya** [comment]
скинь пример, как пробовать, я проверю

**Comment by utya** [comment]
> Похоже, что Mqtt Explorer имя сервера не проверяет
mqtt старые сертификаты, поэтому у него там чёто сломано, они ждут обновления electron

**Comment by alutov** [comment]
Я сгенерил сертификаты на имя homeassistant. У меня имя хоста HA именно такое. Вбил сертификат в эксплорер, все нормально, проверяю из есп - ошибка проверки сертификата. День не мог понять, почему так , потом нашел опцию отключения проверки имени хоста - все стало нормально. Я думаю, что имя хоста это то, что пишется в поле сервера мктт или же полная строка имя сервера : порт. Сам не проверял.
