### ISSUE TITLE
Mqtt device tracker

### ISSUE THREAD

**Issue by DmytroMelnyk** [alutov/ESP32-R4sGate-for-Redmond#98]
У home assistant [есть такая фича](https://www.home-assistant.io/integrations/device_tracker.mqtt/) , что он может трекать устройства по mqtt топику. Можно ли публиковать данные Ble монитора в mqtt? Для выбранных мак адресов например

**Comment by alutov** [comment]
Не совсем понял, о чем речь. Данные BLE монитора публикуются в mqtt. Для этого нужно установить для интересующего устройства ненулевой тайм-аут.

**Comment by DmytroMelnyk** [comment]
а, точно, да. Работает если установить таймаут != 0. Спасибо. Просто что то читал описание несколько раз, так и не понял что нужно сделать чтобы трекались устройства
